config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elif getattr(settings, 'INSECURE_MEDIA', False):
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

handler404 = 'main.views.error_404_view'
handler500 = 'main.views.error_500_view'
handler403 = 'main.views.error_403_view'
handler400 = 'main.views.error_400_view'

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from .views import SiteMapView, Signup, Login, AnimeList, AnimeDetail, EpisodeDetail, SearchBar,  Profile, Help, ContactView, SuggestionView, RedirectToConversation, ConversationList, HelpChat

# URLs para poder acceder a las vistas de la aplicación
urlpatterns = [
    path('sitemap/', SiteMapView.as_view(), name='sitemap'),

    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="anime_list"), name='logout'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('', AnimeList.as_view(), name='anime_list'),
    path('anime/<str:pk>/', AnimeDetail.as_view(), name='anime_detail'),
    path('<str:anime_title>/episode-<int:episode_number>/', EpisodeDetail.as_view(), name='episode_detail'),

    path('search/', SearchBar.as_view(), name='search'),
    path('profile/<int:pk>/', Profile.as_view(), name='profile'),

    path('help/', Help.as_view(), name='help'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('suggestion/', SuggestionView.as_view(), name='suggestion'),
    path('conversations/redirect/', RedirectToConversation.as_view(), name='home_redirect'),
    path('conversations/', ConversationList.as_view(), name='conversation_list'),
    path('help-chat/<int:pk>/', HelpChat.as_view(), name='conversation_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
import os

# Define la ruta de subida de íconos de usuario
def user_icon(instance, filename):
    folder_name = instance.username.replace(' ', '_')
    return os.path.join('users', folder_name, filename)

# Define la ruta para las imágenes del anime
def anime_image_upload_path(instance, filename):
    folder_name = instance.title.replace(' ', '_')
    return os.path.join('anime', folder_name, filename)

# Define la ruta para la imagen del capitulo
def anime_image_episode(instance, filename):
    folder_name = instance.anime.title.replace(' ', '_')
    episode_folder = f"episode_{instance.episode_number}"
    return os.path.join('anime', folder_name, 'episodes', episode_folder, filename)


# Modelo de Usuario 
class User(AbstractUser):
    icon = models.ImageField(upload_to=user_icon, default="users/default.png", blank=True)
    favorite_animes = models.ManyToManyField('Anime', related_name='favorited_by', blank=True)

    def __str__(self):
        return self.username

    # Elimina la foto de perfil anterior si cambia
    def save(self, *args, **kwargs):
        try:
            old_user = User.objects.get(pk=self.pk)
            if old_user.icon and old_user.icon.url != self.icon.url and "default.png" not in old_user.icon.url:
                old_user.icon.delete(save=False)
        except User.DoesNotExist:
            pass
        super().save(*args, **kwargs)

#  Modelo de las categorias
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

# Modelo de los Animes
class Anime(models.Model):
    title = models.CharField(max_length=255, primary_key=True, unique=True)
    description = models.TextField()
    image_detail = models.ImageField(upload_to=anime_image_upload_path, null=True, blank=True)
    image_card = models.ImageField(upload_to=anime_image_upload_path, null=True, blank=True)
    release_date = models.DateField()
    total_episodes = models.IntegerField()
    like_count = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name='animes', blank=True)

    def __str__(self):
        return self.title

# Modelo de los episodios, que esta relacionado por anime
class Episode(models.Model):
    title = models.CharField(max_length=255, primary_key=True, unique=True)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name='episodes')
    episode_number = models.IntegerField()
    release_date = models.DateField()
    video_url = models.URLField(null=True, blank=True, help_text="URL server")
    image_url = models.ImageField(upload_to=anime_image_episode, null=True, blank=True)

    class Meta:
        unique_together = ('anime', 'episode_number')

    def __str__(self):
        return f"{self.anime.title} - Episode {self.episode_number}"
    
# Modelo de los conmentarios, que esta relacionado por anime y episodio
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name='comments')
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE, related_name='comments', null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.anime.title} - {self.episode}"
    
# Modelo de las sugerencias
class Suggestion(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    subject = models.CharField(max_length=150)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Sugerencia de {self.user.username if self.user else 'Anónimo'}"
    
# Modelo de las conversaciones
class Conversation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='conversations')

    def __str__(self):
        return f"Conversación con {self.user.username}"

# Modelo del chat de ayuda
class HelpMessage(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='received_messages')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"De {self.sender.username} para {self.recipient.username if self.recipient else 'todos'}"

main/forms.py
from django import forms
from main.models import User, Suggestion, HelpMessage

# Formulario de registro de usuario
class CustomUserCreationForm(forms.ModelForm):
    # Se pone un minimo de 8 caracteres para las contraseñas para verificar desde el frontend
    password1 = forms.CharField(label="Contraseña",widget=forms.PasswordInput(attrs={'minlength': 8}))
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput(attrs={'minlength': 8}))

    class Meta:
        model = User
        fields = ['username', 'email']

    # Se verifica si el correo electrónico ya está en uso y si las contraseñas coinciden desde el backend
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Ya existe una cuenta con este correo electrónico.")
        return email

    # Se verifica si la contraseña1 y contraseña2 coinciden
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        return password2
    
    # Se guarda el usuario con la contraseña encriptada
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    

# Formulario de Contacto
class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label="Nombre")
    email = forms.EmailField(label="Correo electrónico")
    subject = forms.CharField(max_length=150, required=False, label="Asunto")
    message = forms.CharField(widget=forms.Textarea, label="Mensaje")


# Formulario de sugerencias/buzón
class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestion
        fields = ['subject','message']


# Formulario de chat de ayuda
class HelpMessageForm(forms.ModelForm):
    class Meta:
        model = HelpMessage
        fields = ['message']
        widgets = {'message': forms.Textarea(attrs={'placeholder': 'Escribe algo....',})}

main/templates/anime_detail.html
{% extends "base.html" %}

{% block title %}{{ anime.title }} - Anime Detail{% endblock %}

{% block header_fullwidth %}
    <!-- Portada del anime -->
    <div class="w-full relative">
        <div class="relative w-full h-[550px]">
            <img src="{{ anime.image_detail.url }}" alt="{{ anime.title }}"
                class="absolute w-full h-full object-cover z-0">
            <div class="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-transparent z-10"></div>

            <div class="relative z-30 p-6 md:p-20 max-w-5xl">
                <h1 class="text-4xl md:text-5xl font-bold text-white drop-shadow mb-4">{{ anime.title }}</h1>
                <p class="text-white text-sm md:text-base mb-6">{{ anime.description }}</p>
                <a href="{% url 'episode_detail' anime_title=anime.title episode_number=1 %}" class="inline-flex items-center gap-2 [background-color:#FFBC0E] px-6 py-2 rounded-sm hover:bg-yellow-600 transition">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="black" class="bi bi-play-fill" viewBox="0 0 16 16">
                        <path d="m11.596 8.697-6.363 3.692c-.54.313-1.233-.066-1.233-.697V4.308c0-.63.692-1.01 1.233-.696l6.363 3.692a.802.802 0 0 1 0 1.393"/>
                    </svg>
                    <span class="font-semibold text-black">COMENZAR A VER</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <!-- Mostrar los episodios de los animes -->
    <section class="">
        <h2 class="text-2xl font-semibold text-white mb-4">Episodios</h2>
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5 gap-4">
            {% for episode in episodes %}
                <div class="relative rounded-md overflow-hidden shadow-md hover:scale-[1.02] transition duration-200">
                    <a href="{% url 'episode_detail' anime_title=anime.title episode_number=episode.episode_number %}">
                        <img src="{{ episode.image_url.url }}" alt="{{ episode.title }}" class="w-full">
                    </a>
                    <div class="p-2 text-md">
                        <p class="text-white"><span class="text-yellow-400 font-bold">E{{ episode.episode_number }}</span> - {{ episode.title }}</p>
                        <p class="text-gray-400 text-sm">Fecha: {{ episode.release_date }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'js/header.js' %}"></script>
    {% block extra_scripts %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Mi sitio{% endblock %}</title>
</head>
<body  class="bg-black min-h-screen flex flex-col">
    <!-- Alertas de errores -->
    {% if messages %}
        <div class="fixed top-4 right-4 space-y-2 z-50">
            {% for message in messages %}
            <div
                class="px-4 py-3 rounded shadow
                {% if message.tags == 'success' %}bg-green-100 border-green-400 text-green-700{% endif %}
                {% if message.tags == 'error'   %}bg-red-100   border-red-400   text-red-700  {% endif %}
                {% if message.tags == 'warning' %}bg-yellow-100 border-yellow-400 text-yellow-700{% endif %}
                {% if message.tags == 'info'    %}bg-blue-100  border-blue-400   text-blue-700 {% endif %}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <!-- Menú de navegación (Navbar)-->
    <header style="background-color: #11111F;" class="text-white py-2 h-16">
        <div class="container mx-auto flex justify-between items-center">
            <div class="flex items-center space-x-8">
                <div class="flex items-end space-x-2">
                    <a href="{% url 'anime_list' %}"><img src="{% static 'images/logo.png' %}" alt="TakosuAnime" class="h-12"></a>
                </div>
                <a href="{% url 'anime_list' %}" class="text-white hover:text-yellow-400">Inicio</a>
                <a href="{% url 'help' %}">Ayuda</a>
            </div>

            <div class="flex items-center space-x-4">
                <div class="flex items-center relative">
                    <a href="{% url 'search' %}" class="text-white h-10 w-10 flex items-center justify-center  hover:text-yellow-400">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                        </svg>
                    </a>
                </div>
                <div class="relative">
                    {% if request.user.is_authenticated %}
                        <button id="profileMenuButton" class="inline-block focus:outline-none">
                            <img src="{{ user.icon.url }}" alt="{{ user.username }}" class="w-10 h-10 rounded-full object-cover" />
                        </button>

                        <div style="background-color: #11111F;" id="profileMenu" class="hidden absolute w-48 rounded-lg shadow-lg py-2 z-10">
                            <a href="{% url 'profile' user.id %}" class="block px-4 py-2 text-white hover:text-yellow-500">
                                Perfil
                            </a>
                            <form action="{% url 'logout' %}" method="post" class="block">
                                {% csrf_token %}
                                <button type="submit" class="w-full text-left px-4 py-2 text-white hover:text-yellow-500">
                                    Cerrar Sesión
                                </button>
                            </form>
                        </div>
                    {% else %}
                        <a href="{% url 'login' %}" class="text-white py-2 px-4 rounded-md hover:text-yellow-500">Iniciar Sesión</a>
                        |
                        <a href="{% url 'signup' %}" class="text-white py-2 px-4 rounded-md hover:text-yellow-500">Registrarse</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    {% block header_fullwidth %}{% endblock %} 

    <!-- Mostrar el contenido de las diferentes páginas-->
    <main class="container mx-auto py-8 flex-grow">
        {% block content %}

        {% endblock %}
    </main>

    <!-- Footer -->
    <footer style="background-color: #11111F;" class="text-white py-8">
        <div class="container mx-auto flex flex-col md:flex-row md:gap-x-20 justify-center items-start text-sm pt-5">
            <div class="px-2">
                <span class="font-semibold text-base">Navegación</span>
                <div class="flex flex-col space-y-1 pt-2">
                    <a href="{% url 'anime_list' %}">Inicio</a>
                    <a href="{%  url 'search' %}">Buscar</a>
                    <a href="{% url 'sitemap' %}">Mapa del Sitio</a>
                </div>
            </div>

            <div class="px-2">
                <span class="font-semibold text-base">TakosuAnime</span>
                <div class="flex flex-col pt-2 space-y-1">
                    <a href="{% url 'help' %}">Ayuda</a>
                    <a href="{% url 'suggestion' %}">Buzón</a>
                    <a href="{% url 'contact' %}">Contáctanos</a>
                </div>
            </div>

            <div class="px-2">
                <span class="font-semibold text-base">Cuenta</span>
                <div class="flex flex-col pt-2 space-y-1">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'profile' user.id %}">Perfil</a>
                    <form action="{% url 'logout' %}" method="post" class="block">
                        {% csrf_token %}
                        <button type="submit" class="hover:[color:#FFBC0E]">
                            Cerrar Sesión
                        </button>
                    </form>
                {% else %}
                    <a href="{% url 'login' %}">Iniciar Sesión</a>
                    <a href="{% url 'signup' %}">Registrarse</a>
                {% endif%}
                    <a href="{% url 'home_redirect' %}">Chat</a>
                </div>
            </div>
        </div>
        
        <div class="text-sm text-gray-400 text-center pt-8" >
            © 2025 TakosuAnime.
        </div>
    </footer>
</body>
</html>

main/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}Contáctanos{% endblock %}

{% block content %}
    <div class="max-w-2xl mx-auto [background-color:#11111F] p-8 rounded-lg text-white">
        <h2 class="text-3xl font-bold mb-4">Contáctanos</h2>

        <p class="mb-6">
            <span class="font-bold">¿Necesitas ayuda?</span> Completa el formulario y te responderemos lo antes posible o ponte en contacto directo con el 
            <a href="{% url 'home_redirect' %}" class="font-bold hover:underline">chat de ayuda</a>.
        </p>

        <!-- Formulario para enviar el correo al administrador -->
        <form method="post" action="{% url 'contact' %}" class="space-y-4">
            {% csrf_token %}
            <div>
                <label for="id_name" class="block text-sm mb-1">Nombre <span class="text-red-500">*</span></label>
                <input type="text" name="name" id="id_name" required class="bg-gray-200 text-black w-full px-3 py-2 rounded focus:outline-none" />
            </div>
            <div>
                <label for="id_email" class="block text-sm mb-1">Correo electrónico <span class="text-red-500">*</span></label>
                <input type="email" name="email" id="id_email" required class="bg-gray-200 text-black w-full px-3 py-2 rounded focus:outline-none" />
            </div>
            <div>
                <label for="id_subject" class="block text-sm mb-1">Asunto</label>
                <input type="text" name="subject" id="id_subject" class="bg-gray-200 text-black w-full px-3 py-2 rounded focus:outline-none" />
            </div>
            <div>
                <label for="id_message" class="block text-sm mb-1">Mensaje <span class="text-red-500">*</span></label>
                <textarea name="message" id="id_message" rows="5" required class="bg-gray-200  text-black w-full px-3 py-2 rounded focus:outline-none"></textarea>
            </div>
            <button type="submit" class="[background-color:#FFBC0E] font-semibold hover:bg-yellow-600 text-black px-4 py-2 rounded">
                Enviar mensaje
            </button>
        </form>

        <hr class="my-8 border-gray-700" />

        <div class="space-y-4">
            <p><strong>Email:</strong> adrianlolobre@gmail.com</p>
            <p><strong>Horario de atención:</strong> Lunes a Viernes de 9:00 a 18:00</p>
        </div>
    </div>
{% endblock %}

main/templates/conversation_list.html
{% extends "base.html" %}

{% block title %}Conversaciones{% endblock %}

{% block content %}
    <h1 class="text-white text-xl font-bold">Lista de Conversaciones</h1>

    <!-- Muestra las conversaciones del chat del lado del administrador -->
    <ul>
    {% for conversation in conversations %}
        <li class="py-2">
            <a href="{% url 'conversation_detail' conversation.pk %}" class="text-white py-3 px-8 text-center [background-color:#11111F] rounded-md block h-12 w-1/4">
                Conversación con {{ conversation.user.username }}
            </a>
        </li>
    {% empty %}
        <li class="text-white">No hay conversaciones.</li>
    {% endfor %}
    </ul>
{% endblock %}

main/templates/error.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Error {{ status_code }} - TakosuAnime</title>
</head>
<body class="bg-black min-h-screen flex items-center justify-center">
    <div class="col-span-full items-center justify-center text-center">
        <img src="{% static 'images/error.gif' %}" alt="No results" class="mx-auto mt-4">
        <h2 class="text-4xl font-semibold text-white mt-4 mb-4 italic">Ooops!!!...</h2>
        <p class="text-gray-400 text-2xl">{{ message }}</p>
        <a href="{% url 'anime_list' %}" class="inline-block hover:[color:#FFBC0E] hover:underline text-white text-lg mt-8 px-4">
            Volver al inicio
        </a>
    </div>
</body>
</html>

main/templates/help_chat.html
{% extends "base.html" %}
{% load static %}
{% load form_filters %}

{% block extra_scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const messageInput = document.querySelector('#id_message');
            const form = document.querySelector('#message-form');
            const chatBox = document.querySelector('#chat-box');

            // Mostrar el último mensaje
            chatBox.scrollTop = chatBox.scrollHeight;

            // Enviar mensaje con Enter
            messageInput.addEventListener('keydown', function(e) {
                if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    form.submit();
                }
            });
        });
    </script>
{% endblock %}

{% block title %}Chat de Ayuda{% endblock %}
{% block content %}
    <h2 class="text-white text-2xl font-bold">Chat de Ayuda</h2>

    <!-- Mostrar Mensajes -->
    <div class="[background-color:#11111F] relative w-1/2 mx-auto rounded-lg" style="height:650px;">
        <div id="chat-box" class="overflow-y-auto h-[600px] p-4 space-y-2">
            {% for msg in chat_messages %}
                {% if msg.sender == request.user %}
                    <!-- Mostrar los mensajes que envio el usuario -->
                    <div class="flex justify-end">
                        <div class="flex items-end gap-2 max-w-[70%]">
                            <div class="[background-color:#FFBC0E] text-black p-3 rounded-lg rounded-br-none">
                                <p>{{ msg.message }}</p>
                                <small class="text-gray-800 text-xs">{{ msg.created_at }}</small>
                            </div>
                            <img src="{% if msg.sender.icon %}{{ msg.sender.icon.url }}{% else %}{% static 'default_icon.png' %}{% endif %}"
                                alt="{{ msg.sender.username }}"
                                class="w-8 h-8 rounded-full object-cover">
                        </div>
                    </div>
                {% else %}
                    <!-- Mostrar los mensajes que se enviaron al usuario -->
                    <div class="flex justify-start">
                        <div class="flex items-end gap-2 max-w-[70%]">
                            <img src="{% if msg.sender.icon %}{{ msg.sender.icon.url }}{% endif %}"
                                alt="{{ msg.sender.username }}"
                                class="w-8 h-8 rounded-full object-cover">
                            <div class="bg-gray-800 text-white p-3 rounded-lg rounded-bl-none">
                                <p><strong>{{ msg.sender.username }}</strong>: {{ msg.message }}</p>
                                <small class="text-gray-300 text-xs">{{ msg.created_at }}</small>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% empty %}
                <p class="text-white">No hay mensajes aún.</p>
            {% endfor %}
        </div>

        <!-- Enviar mensaje -->
        <form method="post" class="absolute bottom-0 left-0 right-0 p-2" id="message-form">
            {% csrf_token %}
            <div class="flex items-center gap-2">
                {{ form.message|add_class:"w-full h-10 px-4 py-2 rounded bg-white resize-none overflow-hidden" }}
                <button type="submit" class="[background-color:#FFBC0E] text-black px-2 py-2 rounded-full hover:bg-yellow-600">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
                    </svg>
                </button>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}
    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
        {% for anime in animes %}
            <a href="{% url 'anime_detail' anime.title %}" class="w-[210px]">
                <div class="shadow-md overflow-hidden">
                    <img src="{{ anime.image_card.url }}" alt="{{ anime.title }}" class="h-[300px] object-cover rounded-sm">
                    <div class="p-2">
                        <h2 class="text-sm font-bold text-center text-white">{{ anime.title }}</h2>
                        <p class="text-xs text-gray-200 text-center">{{ anime.total_episodes }} Episodios</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% load form_filters %}
    
{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
    <div class="flex items-center justify-center">
        <form method="post" class="bg-white p-8 rounded-lg shadow-md w-full max-w-lg"  style="background-color: #11111F;">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="bg-red-100 border-red-400 text-red-700 px-4 py-2 rounded mb-4">
                    <ul class="list-disc pl-5">
                    {% for err in form.non_field_errors %}
                        <li>{{ err }}</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <h2 class="text-2xl font-bold text-center mb-6 text-white">Iniciar Sesión</h2>
            <div class="mb-4">
                <label for="username" class="block text-sm font-medium text-white">Usuario</label>
                {{ form.username|add_class:"block w-full px-4 py-2 mt-1 border border-gray-300 rounded-sm bg-gray-200" }}
            </div>
            <div class="mb-4">
                <label for="password" class="block text-sm font-medium text-white">Contraseña</label>
                {{ form.password|add_class:"block w-full px-4 py-2 mt-1 border border-gray-300 rounded-sm bg-gray-200" }}
            </div>
            <button type="submit" class="[background-color:#FFBC0E] font-semibold w-full py-2 px-4 rounded-sm hover:bg-yellow-600">
                Iniciar Sesión
            </button>
            <p class="text-center text-sm text-white mt-2">
                <a href="{% url 'password_reset' %}" class="hover:underline">¿Olvidaste tu contraseña?</a>
            </p>
            <p class="text-center text-sm text-white mt-4">
                ¿No tienes una cuenta? <a href="{% url 'signup' %}" class="hover:underline">Registrarse</a>
            </p>
        </form>
    </div>
{% endblock %}

main/templates/password_reset.html
{% extends "base.html" %}
{% load form_filters %}

{% block title %}Recuperar Contraseña{% endblock %}

{% block content %}
    <div class="flex items-center justify-center">
        <form method="post" class="bg-white p-8 rounded-lg shadow-md w-full max-w-lg" style="background-color: #11111F;">
            <h2 class="text-2xl font-bold text-center mb-6 text-white">Recuperar Contraseña</h2>
            {% csrf_token %}
            <label for="email" class="block text-sm font-medium text-white">Correo electrónico</label>
            {{ form.email|add_class:"block w-full px-4 py-2 mt-1 border border-gray-300 rounded-sm mb-4" }}
            <button type="submit" class="[background-color:#FFBC0E] w-full py-2 px-4 rounded-sm hover:bg-yellow-600 text-white">Enviar enlace</button>
        </form>
    </div>
{% endblock %}